[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "gotmpl"
language-servers = ["gopls", "vscode-html-language-server", "tailwindcss-ls"]
file-types = ["gotmpl", "gohtml", "go.html"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
file-types = ["gotmpl", "gohtml", "html", "htm"]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "php"
language-servers = [ "intelephense", "tailwindcss-ls" ]

[[language]]
name = "nginx"
scope = "source.nginx"
injection-regex = "nginx"
file-types = ["conf"]
